// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sport_Calendar.Infrastructure.Data;

#nullable disable

namespace Sport_Calendar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_event");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_date");

                    b.Property<TimeOnly>("EventTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_time");

                    b.Property<int?>("LocalTeamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("local_team");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("place_id");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sport_id");

                    b.Property<int?>("VisitTeamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visit_team");

                    b.HasKey("Id");

                    b.HasIndex("LocalTeamId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("SportId");

                    b.HasIndex("VisitTeamId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_place");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("place");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_price");

                    b.Property<bool>("Vip")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vip");

                    b.HasKey("Id");

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sport");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Individual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("individual");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Sport", (string)null);
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_team");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_place");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sport");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("SportId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Event", b =>
                {
                    b.HasOne("Sport_Calendar.Domain.Models.Team", "LocalTeam")
                        .WithMany()
                        .HasForeignKey("LocalTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sport_Calendar.Domain.Models.Place", "Place")
                        .WithMany("Events")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sport_Calendar.Domain.Models.Sport", "Sport")
                        .WithMany("Events")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sport_Calendar.Domain.Models.Team", "VisitTeam")
                        .WithMany()
                        .HasForeignKey("VisitTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalTeam");

                    b.Navigation("Place");

                    b.Navigation("Sport");

                    b.Navigation("VisitTeam");
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Team", b =>
                {
                    b.HasOne("Sport_Calendar.Domain.Models.Place", "Place")
                        .WithMany("Teams")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sport_Calendar.Domain.Models.Sport", "Sport")
                        .WithMany("Teams")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Place", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Sport_Calendar.Domain.Models.Sport", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
